import type { NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { trpc } from "../utils/trpc";
import Menu from "../components/Menu";
import Banner from "../components/Banner";
import ItemCard from "../components/ItemCard";
import dynamic from 'next/dynamic'
import Footer from "../components/Footer";
import React from "react";
import type { Item } from "../types/types";

const Header = dynamic(
  () => import('../components/Header'),
  { ssr: false }
)

const Home: NextPage = () => {

  const [cartItems, setCartItems] = React.useState(Array<Item>());

  const cartModal = (
    <>
      <input type="checkbox" id="cart-modal" className="modal-toggle" />
      <div className="modal">
        <div className="modal-box relative">
          <label htmlFor="cart-modal" className="btn btn-sm btn-circle absolute right-2 top-2">✕</label>
          {
            cartItems.length === 0 ? (
              <p className="font-poppins text-md">Your cart is empty</p>
            ) : (
              <div className='flex flex-col'>
                <div className='flex justify-between items-center'>
                  <p className='font-poppins text-2xl'>Your Cart</p>
                  <p className='font-poppins text-2xl'>{cartItems.length} items</p>
                </div>
                <div className='flex flex-col space-y-4 mt-4'>
                  {
                    cartItems.map((item, index) => (
                      <div key={index} className='flex justify-between items-center'>
                        <div className='flex items-center'>
                          <img src={item.image} alt={item.name} className='w-20 h-20 object-contain' />
                          <div className='flex flex-col ml-4'>
                            <p className='font-poppins text-md'>{item.name}</p>
                            <p className='font-poppins text-md'>{item.price}€</p>
                          </div>
                        </div>
                        <button className='font-poppins text-md bg-primary text-white rounded-md p-2'
                          onClick={() => {
                            setCartItems((prev) => prev.filter((_, i) => i !== index))
                          }}>
                          Remove
                        </button>
                      </div>
                    ))
                  }
                </div>
              </div>
            )}
        </div>
      </div>
    </>
  )

  return (
    <>
      <Head>
        <title>Eurospin</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Header cartItems={cartItems} />
      <main className="bg-background min-h-screen">
        {cartModal}
        <Menu />
        <Banner />
        <div className="mt-6">
          <p className="font-poppins uppercase text-lg flex justify-center">LE MIGLIORI OCCASIONI LE TROVI SOLO NELL'ONLINE STORE EUROSPIN</p>
        </div>
        <div className="w-3/4 mx-auto p-6 flex items-center space-x-4">
          <ItemCard image="/ariete.jpg" name="Ariete Piastra elettrica" price={42.99} setCartItems={setCartItems} />
          <ItemCard image="/asciugatrice.jpg" name="Hoover asciugatrice 10kg" price={449.99} setCartItems={setCartItems} />
          <ItemCard image="/borsa-frigo.jpg" name="Borsa frigo 10L termica" price={9.99} setCartItems={setCartItems} />
          <ItemCard image="/majestic.jpg" name="Majestic telefono skid" price={39.99} setCartItems={setCartItems} />
        </div>
      </main>
      <Footer />

    </>
  );
};

export default Home;
