import type { NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { trpc } from "../utils/trpc";
import Menu from "../components/Menu";
import Banner from "../components/Banner";
import ItemCard from "../components/ItemCard";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Eurospin</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main className="bg-background min-h-screen">
        <Menu />
        <Banner />
        <div className="mt-6">
          <p className="font-poppins uppercase text-lg flex justify-center">LE MIGLIORI OCCASIONI LE TROVI SOLO NELL'ONLINE STORE EUROSPIN</p>
        </div>
        <div className="w-3/4 mx-auto p-6 flex items-center space-x-4">
          <ItemCard image="/ariete.jpg" title="Ariete Piastra elettrica" price={42.99} />
          <ItemCard image="/asciugatrice.jpg" title="Hoover asciugatrice 10kg" price={449.99} />
          <ItemCard image="/borsa-frigo.jpg" title="Borsa frigo 10L termica" price={9.99} />
          <ItemCard image="/majestic.jpg" title="Majestic telefono skid" price={39.99} />
        </div>
      </main>

    </>
  );
};

export default Home;
