import { NextPage } from 'next';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import React from 'react'
import { useAccount, useContractWrite, usePrepareContractWrite, useWaitForTransaction } from 'wagmi';
import Banner from '../components/Banner';
import Footer from '../components/Footer';
import ItemCard from '../components/ItemCard';
import { Item } from '../types/types';
import { nftAddress, tokenAddress } from '../utils/constants';
import SpinTokenABI from "../../../contracts/abi/spintoken.json"
import Ring from '@uiball/loaders/dist/components/Ring';



const Header = dynamic(
  () => import('../components/Header'),
  { ssr: false }
)

const Menu = dynamic(
  () => import('../components/Menu'),
  { ssr: false }
)



function productDetails() {

  const [cartItems, setCartItems] = React.useState(Array<Item>());
  const [selectedTab, setSelectedTab] = React.useState('home');
  const { address } = useAccount();



  const { config, isSuccess: succ, isError, isLoading: load } = usePrepareContractWrite({
    addressOrName: tokenAddress,
    contractInterface: SpinTokenABI,
    functionName: 'transferTokens',
    args: [address, 10],
    onError(err) {
      console.log(err)
    },
    onSuccess(data) {
      console.log(data)
    },
  });


  const { data, isLoading, write: sendCashback } = useContractWrite(config)
  const { isSuccess, isLoading: isLoadingTx } = useWaitForTransaction({
    hash: data?.hash,
  })


  return (
    <>
      <Head>
        <title>Eurospin</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Header cartItems={cartItems} />
      <main className="bg-background min-h-screen">
        <img className="m-auto t-0 l-0 r-0 b-0" src='https://www.eurospin.it/wp-content/uploads/Header_Pagina_Pasta_Bronzo.jpg'></img>

        <div className="flex w-100 px-80 pt-10 h-auto flex-wrap">
          <div className='w-1/2 p-10'>
            <img src='https://www.eurospin.it/wp-content/uploads/Logo_Bronzo.png'></img>
          </div>
          <div className='w-1/2 my-5'>
            <h2 className='text-5xl font-bold mb-5 text-black font-poppins'>Tre Mulini</h2>
            <p className='text-black font-poppins'>Tre Mulini è la linea di Eurospin dei prodotti derivati dal grano: panificati, paste di semola e all’uovo, cereali, crackers, farine e molto altro.
              Tra le specialità di Tre mulini troverai la pasta di semola trafilata al bronzo, tagliatelle e tagliolini all’uovo,  paste fresche e ripiene per creare tutti i primi piatti che desideri.
              Per la prima colazione perfetta, prova invece i cereali in tutte le loro golose varianti: dai classici corn-flakes a quelli integrali con frutti rossi, fino ad arrivare al müesli croccante, buono e ricco di fibre.
              Tra i prodotti dei Tre Mulini ci sono, infine, tantissime specialità surgelate da infornare e gustare: pizze, focacce farcite e primi piatti pronti ti aspettano al banco surgelati!</p>
          </div>
          <video className="m-auto t-0 l-0 r-0 b-0 " controls>
            <source src="https://www.eurospin.it/wp-content/uploads/200312_Eurospin_spaghetti_v3.mp4?_=1"></source>
          </video>
          <div className='text-black mt-10 font-poppins'>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis tincidunt sollicitudin nisl vel facilisis. Praesent a mi non enim volutpat eleifend. Proin accumsan, est eget iaculis volutpat, urna urna imperdiet turpis, in eleifend dolor ipsum eu arcu. Etiam scelerisque lectus pharetra magna tempus tincidunt. Suspendisse in libero suscipit elit tempor pretium. Integer suscipit orci quis lectus euismod dignissim. Suspendisse diam est, pulvinar id ipsum ac, luctus aliquam est. Mauris tortor ipsum, gravida vel sodales nec, elementum quis ipsum. Ut euismod iaculis ipsum sed tempor. Etiam eleifend a erat sed aliquet. Aenean egestas venenatis pellentesque.
              Ut vel odio quis dui vehicula sagittis. Aliquam condimentum ipsum eu dignissim congue. Proin sed commodo elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam sodales felis at rutrum sodales. Nullam varius ac massa in volutpat. Nulla viverra ipsum non ante volutpat blandit. Nam viverra arcu a turpis facilisis aliquet. Quisque non posuere quam. Aenean at fermentum est. Vivamus ligula dui, eleifend sed rhoncus ac, condimentum eget nisi. Phasellus dapibus tortor id sem volutpat consequat.
              Duis porttitor lacus purus, eget lobortis massa condimentum non. Suspendisse pellentesque tortor nec est tristique varius. Sed risus sapien, maximus interdum dolor quis, placerat ultrices mi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam dapibus leo sed sem fermentum pharetra. Mauris blandit pharetra magna, id iaculis arcu viverra sed. Curabitur rutrum est ac orci suscipit, et iaculis magna tincidunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur scelerisque interdum nulla eu convallis.</p>
          </div>
        </div>


        <div className='px-40 py-20'>
          {!isSuccess ? <button className="w-full px-5 py-5 bg-primary rounded text-white text-xl font-semibold font-poppins" onClick={() => {
            sendCashback?.()
          }}>
            <div className="flex space-x-8 items-center">
              <p className="flex-1 font-poppins text-md">{isLoading || isLoadingTx ? "Riscatto in corso" : "Riscatta 10 punti fedeltà"}</p>
              {isLoading || isLoadingTx && <Ring size={30} color="#ffffff" />}
            </div>
          </button> :
            <p className=" font-poppins text-xl text-center text-primary">Hai riscattato 10 punti fedeltà</p>}
        </div>
      </main>
      <Footer />
    </>
  );
}

export default productDetails;